#ifndef SETTINGSDEFINES_H
#define SETTINGSDEFINES_H

#define DEFAULT_SETTINGS_KEY_AUTOSAVE_ENABLED true
#define DEFAULT_SETTINGS_KEY_AUTOSAVE_INTERVAL 10

#define SETTINGS_KEY_MAIN_WINDOW_STATE "mainWindowState"
#define SETTINGS_KEY_MAIN_WINDOW_GEOMETRY "mainWindowGeometry"
#define SETTINGS_KEY_MAIN_WINDOW_POS "mainWindowPos"
#define SETTINGS_KEY_MAIN_WINDOW_MAXIMAZID "mainWindowMaximazed"
#define SETTINGS_KEY_MAIN_WINDOW_SIZE "mainWindowSize"
#define SETTINGS_KEY_AUTOSAVE_ENABLED "autosaveEnabled"
#define SETTINGS_KEY_AUTOSAVE_INTERVAL "autosaveInterval"
#define SETTINGS_KEY_LANGUAGE "language"


#endif // SETTINGSDEFINES_H
